name: build and deploy lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::045411470840:role/github-actions-lambda-cicd
          aws-region: us-east-1

      - name: Set up build environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: npm clean-install

      - name: zip it up
        run: zip -r package.zip ./ -x '*.git' -x '.git*'

      - name: push it to s3
        run: |
          aws s3 cp package.zip s3://dreamup.lambda.packages/options-public-gallery-id-handler.zip

      - name: update lambda code
        run: |
          aws lambda update-function-code \
          --function-name "options-public-gallery-id-handler" \
          --s3-bucket dreamup.lambda.packages \
          --s3-key options-public-gallery-id-handler.zip \
          --publish
